---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
useGitignore: true
dictionaryDefinitions:
  - name: cspell-words
    path: cspell-words.txt
    addWords: true
dictionaries:
  - cspell-words
language: en-US # de-DE
# import:
#   - "@cspell/dict-de-de"
ignorePaths:
  - '.*.js'
  - '.*.ts'
  - '.*'
  - 'build'
  - 'cspell.config.yaml'
  - 'dist'
  - 'package*.json'
  - 'scripts/**'
  - 'src/assets/'
