allowBuilds:
  '@parcel/watcher': true
  cypress: true
  esbuild: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - cypress
  - esbuild
  - vue-demi
minimumReleaseAge: 20160 # 2 weeks (in minutes)
minimumReleaseAgeExclude:
  - '@biomejs/biome'
  - '@biomejs/cli-darwin-arm64'
  - '@biomejs/cli-darwin-x64'
  - '@biomejs/cli-linux-arm64-musl'
  - '@biomejs/cli-linux-arm64'
  - '@biomejs/cli-linux-x64-musl'
  - '@biomejs/cli-linux-x64'
  - '@biomejs/cli-win32-arm64'
  - '@biomejs/cli-win32-x64'
  - qs@6.15.2
  - tmp@0.2.6
  - cypress@15.16.0
  - yauzl@3.3.1
overrides:
  serialize-javascript@<7.0.5: '>=7.0.5'
  serialize-javascript@<=7.0.2: '>=7.0.3'
